tasks:
  - name: terraform
    before: |
      source ./bin/set_tf_alias
      source ./bin/install_terraform_cli
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      source ./bin/set_tf_alias
      source ./bin/install_aws_cli

  - name: python-requirements
    before: |
      cd $PROJECT_ROOT
      pip3 install -r requirements.txt
vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - hashicorp.terraform
    - ms-python.python
ports:
  - name: backend
    port: 5000
    visibility: public